<a href="https://colab.research.google.com/github/drichter98/PyTorchLearningHub/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [43]:
print(torch.__version__)

2.1.0+cu121


In [ ]:
!nvidia-smi

Sat Mar  2 17:49:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Introduction to Tensors

### Creating tensors


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#get dimension
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers --> look at data --> update random numbers --> look at data --> update random numbers`

In [ ]:
# create a random tensor of shape/size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6450, 0.7438, 0.6366, 0.2885],
        [0.9337, 0.4602, 0.4485, 0.7416],
        [0.4088, 0.9221, 0.1795, 0.4350]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
# create tensor with random zeros and ones
test_tensor = torch.rand(size = (2,2))
test_binary_tensor = (test_tensor > 0.5).float()
test_tensor, test_binary_tensor

(tensor([[0.7951, 0.4034],
         [0.3144, 0.7630]]),
 tensor([[1., 0.],
         [0., 1.]]))

### Creating a range of tensors and tensors-like

In [6]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [8]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float 16)
                               device=None, # What device is your tensor on "cpu"/"cuda"
                               requires_grad=False) # Is True if gradients need to be computed for this Tensor, False otherwise
float_32_tensor

tensor([3., 6., 9.])

In [9]:
float_32_tensor.dtype

torch.float32

In [10]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [18]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [19]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get dataype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [21]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5638, 0.4878, 0.1546, 0.2463],
        [0.0391, 0.4386, 0.9476, 0.4827],
        [0.6682, 0.5051, 0.0483, 0.1212]])

In [22]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5638, 0.4878, 0.1546, 0.2463],
        [0.0391, 0.4386, 0.9476, 0.4827],
        [0.6682, 0.5051, 0.0483, 0.1212]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [27]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [28]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [29]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [30]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [32]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimension** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [52]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[1.0381, 1.4908],
        [0.9497, 1.3767]])

In [44]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [45]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [49]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [50]:
tensor @ tensor

tensor(14)

In [47]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.52 ms, sys: 0 ns, total: 1.52 ms
Wall time: 2.97 ms


In [48]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 526 µs, sys: 0 ns, total: 526 µs
Wall time: 433 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

To fix a tensor shape issue, we can manipulate the shape of one of our tensors unsing a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [61]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

print(tensor_A.shape, tensor_B.shape)

tensor_B = tensor_B.T # transpose

# The matrix multiplication operation works when tensor_B is transposed
torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (alias)


torch.Size([3, 2]) torch.Size([3, 2])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [58]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([2, 3]))