<a href="https://colab.research.google.com/github/drichter98/PyTorchLearningHub/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
print(torch.__version__)

2.1.0+cu121


In [5]:
!nvidia-smi

Sat Mar  2 17:49:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Introduction to Tensors

### Creating tensors


In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
#get dimension
scalar.ndim

0

In [15]:
#get tensor back as python int
scalar.item()

7

In [13]:
# vector
vector = torch.tensor([7, 7])

In [14]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [18]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
MATRIX.ndim

2

In [28]:
MATRIX[1]

tensor([ 9, 10])

In [23]:
MATRIX.shape

torch.Size([2, 2])

In [35]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [36]:
TENSOR.ndim

3

In [37]:
TENSOR.shape

torch.Size([1, 3, 3])

In [38]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers --> look at data --> update random numbers --> look at data --> update random numbers`

In [43]:
# create a random tensor of shape/size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6450, 0.7438, 0.6366, 0.2885],
        [0.9337, 0.4602, 0.4485, 0.7416],
        [0.4088, 0.9221, 0.1795, 0.4350]])

In [44]:
random_tensor.ndim

2

In [45]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [51]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [52]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [55]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [56]:
ones.dtype

torch.float32

In [72]:
# create tensor with random zeros and ones
test_tensor = torch.rand(size = (2,2))
test_binary_tensor = (test_tensor > 0.5).float()
test_tensor, test_binary_tensor

(tensor([[0.7951, 0.4034],
         [0.3144, 0.7630]]),
 tensor([[1., 0.],
         [0., 1.]]))